[package]
name = "xmtp-networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmtp-proto = { path = "../xmtp-proto", features = ["proto_full"] }
prost = { version  = "^0.11", features = ["prost-derive"] }
tonic = { version = "^0.9", features = ["tls"] }
tokio = { version = "1.24", features = ["macros", "rt-multi-thread"] }
tonic-reflection = "0.6.0"
tokio-rustls = "0.24.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21.0"
pbjson = "0.5.1"
pbjson-types = "0.5.1"
webpki-roots = "0.23.0"
hyper = "0.14.26"
hyper-rustls = { version = "0.24.0", features = ["http2"]}
tower = "0.4.13"
