version: 2
updates:
  # Maintain dependencies for cargo
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/crates/*"
      - "/bindings/*"
      - "/apps/*"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  # Maintain dependencies for yarn
  - package-ecosystem: "npm"
    directory: "/bindings/wasm"
    schedule:
      interval: "weekly"
    groups:
      wasm-prod:
        dependency-type: "production"
      wasm-dev:
        dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  # Maintain dependencies for yarn
  - package-ecosystem: "npm"
    directory: "/bindings/node"
    schedule:
      interval: "weekly"
    groups:
      node-prod:
        dependency-type: "production"
      node-dev:
        dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
