exclude = [
  ".direnv/**",
  "crates/xmtp_proto/Cargo.toml",
  "crates/xmtp-workspace-hack/Cargo.toml",
]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies"]

[rule.formatting]
reorder_keys = true
