exclude = [
  "**/node_modules/**",
  ".build/**",
  ".direnv/**",
  "crates/xmtp_proto/Cargo.toml",
  "crates/xmtp-workspace-hack/Cargo.toml",
  "**/.direnv/**",
]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true
