[package]
name = "xmtp_macro"
edition = "2024"
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
num_cpus = "1.17"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", default-features = false, features = [
  "parsing",
  "proc-macro",
  "derive",
  "printing",
  "full",
  "clone-impls",
] }

[lib]
proc-macro = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true
