[package]
name = "xmtp_db_test"
edition = "2024"
license.workspace = true
version.workspace = true
description = "local db chaos testing"

[lints]
workspace = true

[dependencies]
derive_builder.workspace = true
diesel.workspace = true
parking_lot.workspace = true
rand.workspace = true
tracing.workspace = true
xmtp-workspace-hack = { version = "0.1", path = "../xmtp-workspace-hack" }
xmtp_common = { workspace = true, features = ["test-utils"] }
xmtp_db = { workspace = true, features = ["test-utils"] }
