[package]
name = "memprofile"
edition = "2024"
license.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
color-eyre.workspace = true
dhat.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
xmtp_common.workspace = true
xmtp_id = { workspace = true, features = ["test-utils"] }
xmtp_mls = { workspace = true, features = ["test-utils"] }
xshell.workspace = true


[[test]]
harness = true
name = "dm_broadcast"

[lints]
workspace = true
