[package]
name = "xmtp_api_d14n"
edition = "2024"
license.workspace = true
version.workspace = true
description = "XMTP Decentralization client implementation according to XIP-49"

[lints]
workspace = true

[dependencies]
arc-swap.workspace = true
async-trait.workspace = true
chrono.workspace = true
derive_builder.workspace = true
futures.workspace = true
hex.workspace = true
http = "1.2"
hyper = { version = "1.7", default-features = false }
impl-trait-for-tuples = "0.2"
itertools.workspace = true
openmls_rust_crypto = { workspace = true }
parking_lot.workspace = true
pbjson-types.workspace = true
pin-project.workspace = true
prost.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tracing.workspace = true
url.workspace = true
xmtp_api_grpc = { workspace = true }
xmtp_common.workspace = true
xmtp_configuration = { workspace = true }
xmtp_cryptography.workspace = true
xmtp_id = { workspace = true }
xmtp_proto = { workspace = true }

# Test Utils
ctor = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
wasm-bindgen-test = { workspace = true, optional = true }
xmtp-workspace-hack = { version = "0.1", path = "../xmtp-workspace-hack" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openmls = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
openmls = { workspace = true, features = ["js"] }


[dev-dependencies]
futures-test.workspace = true
hex.workspace = true
mockall.workspace = true
rstest.workspace = true
tokio.workspace = true
# add self to auto enable test utils
xmtp_api_d14n = { path = ".", features = ["test-utils"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
ctor.workspace = true
proptest = { workspace = true, features = [
  "std",
  "fork",
  "timeout",
  "bit-set",
] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true
# needed for rstest
futures-timer = { workspace = true, features = ["wasm-bindgen"] }
proptest = { workspace = true, features = ["std"] }


[features]
test-utils = [
  "xmtp_api_grpc/test-utils",
  "xmtp_common/test-utils",
  "xmtp_proto/test-utils",
  "dep:mockall",
  "dep:ctor",
  "dep:wasm-bindgen-test",
]
v3 = []
d14n = []
dev = ["xmtp_configuration/dev", "xmtp_proto/dev"]
