name: xmtp_bindings_flutter
description: low-level flutter bindings to libxmtp
repository: https://github.com/xmtp/libxmtp
version: 0.0.2-development.1

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^2.0.0-dev.22
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  plugin_platform_interface: ^2.0.2
  uuid: ^4.2.2
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  ffigen: ^9.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  web3dart: ^2.6.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
