[package]
name = "xmtp_pppp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmtp_proto = { path = "../xmtp_proto", features = ["xmtp-message_contents"] }
xmtp_crypto = { path = "../xmtp_crypto" }
prost = { version = "0.11", features = ["prost-derive"] }
base64 = "0.21.4"
# Need to include this as a dep or compile will fail because of a version mismatch
once_cell = "1.18.0"

[dev-dependencies]
libsecp256k1 = { version = "0.7.1", default-features = false, features = [
    "hmac",
    "static-context",
] }
rand = "0.8.5"
