[package]
name = "xdbg"
description = "Debug and Inspection Tool for the XMTP Network"
edition = "2021"
version = "0.1.0"
license.workspace = true

[build-dependencies]
vergen-git2 = { workspace = true, features = ["build"] }

[dependencies]
chrono.workspace = true
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "3.0"
color-eyre = "0.6"
const_format.workspace = true
directories = "6.0"
ecdsa = "0.16"
ethers.workspace = true
fdlimit.workspace = true
fs_extra = "1.3"
hex.workspace = true
indicatif = "0.17"
k256 = "0.13"
lipsum = "0.9"
miniserde = "0.1"
openmls.workspace = true
owo-colors = "4.1"
prost.workspace = true
rand.workspace = true
redb = "2.4"
speedy = "0.8"
tempfile = "3.17"
thiserror.workspace = true
tokio = "1.43"
tracing = { workspace = true, features = ["valuable"] }
tracing-appender = "0.2"
tracing-logfmt.workspace = true
tracing-subscriber = { workspace = true, features = [
  "time",
  "json",
  "chrono",
  "env-filter",
  "valuable",
  "ansi",
] }
url.workspace = true
valuable = { version = "0.1", features = ["derive"] }
xmtp_api_grpc.workspace = true
xmtp_cryptography = { workspace = true, features = ["exposed-keys"] }
xmtp_id.workspace = true
xmtp_mls.workspace = true
xmtp_proto.workspace = true
xxhash-rust = { version = "0.8", features = ["xxh3"] }
