[package]
name = "xdbg"
description = "Debug and Inspection Tool for the XMTP Network"
edition = "2024"
version = "0.1.0"
license.workspace = true

[lints]
workspace = true

[build-dependencies]
vergen-git2 = { workspace = true, features = ["build"] }

[dependencies]
alloy.workspace = true
chrono.workspace = true
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "3.0"
color-eyre.workspace = true
const_format.workspace = true
directories = "6.0"
ecdsa = "0.16"
fdlimit.workspace = true
fs_extra = "1.3"
hex.workspace = true
indicatif = "0.18"
k256 = "0.13"
lipsum = "0.9"
miniserde = "0.1"
num_cpus = "1.16.0"
openmls.workspace = true
owo-colors.workspace = true
prost.workspace = true
rand = { workspace = true, features = ["small_rng"] }
redb = "2.6"
speedy = "0.8"
tempfile = "3.15"
thiserror.workspace = true
tokio = "1.43"
tracing = { workspace = true, features = ["valuable"] }
tracing-appender = "0.2"
tracing-logfmt.workspace = true
tracing-subscriber = { workspace = true, features = [
  "time",
  "json",
  "chrono",
  "env-filter",
  "valuable",
  "ansi",
] }
url.workspace = true
valuable = { version = "0.1", features = ["derive"] }
xmtp_api_d14n.workspace = true
xmtp_api_grpc.workspace = true
xmtp_cryptography = { workspace = true, features = ["exposed-keys"] }
xmtp_db.workspace = true
xmtp_id.workspace = true
xmtp_mls.workspace = true
xmtp_proto.workspace = true
xxhash-rust = { version = "0.8", features = ["xxh3"] }
