[package]
edition = "2024"
name = "xmtp_content_types"
version.workspace = true
license.workspace = true
description = "xmtp content types"

[features]
test-utils = []

[dependencies]
aes-gcm.workspace = true
base64.workspace = true
chrono = { workspace = true, features = ["serde"] }
hex.workspace = true
hkdf.workspace = true
prost = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true

# XMTP/Local
xmtp-workspace-hack = { version = "0.1", path = "../xmtp-workspace-hack" }
xmtp_common.workspace = true
xmtp_proto.workspace = true

[dev-dependencies]
xmtp_common = { workspace = true, features = ['test-utils'] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true
