name: iOS Docs

on:
  push:
    branches: ["main"]
    paths: ["sdks/ios/**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ios-pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"
      - name: Build bindings
        run: nix develop .#ios --command ./sdks/ios/dev/bindings
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install Jazzy
        working-directory: sdks/ios
        run: |
          bundle config path vendor/bundle
          bundle add jazzy
      - name: Generate documentation
        working-directory: sdks/ios
        run: bundle exec jazzy --output ./docs --theme=fullwidth --module=XMTPiOS
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "sdks/ios/docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
