name: Lint TOML
on:
  workflow_call:
jobs:
  lint:
    name: Lint (TOML)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli@0.9.3
      - name: Run format check
        run: taplo format --check --diff
      - name: Run validation check
        run: taplo check
