name: Lint WASM
on:
  workflow_call:
env:
  NIX_DEVSHELL: wasm
jobs:
  lint:
    name: Lint (WASM)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: taiki-e/install-action@just
      - name: Install dependencies
        run: just wasm install-ci
      - name: Lint WASM bindings
        run: just wasm lint
