name: Lint Android

on:
  workflow_call:

jobs:
  lint:
    name: Lint (Android)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
      - name: Build Android Bindings
        run: ./sdks/android/dev/bindings
      - name: Run Spotless Check
        run: nix develop ".#android" --command ./sdks/android/gradlew -p sdks/android spotlessCheck --continue
      - name: Run Android Lint
        run: nix develop ".#android" --command ./sdks/android/gradlew -p sdks/android :library:lintDebug
