name: Lint Android
on:
  workflow_call:
env:
  NIX_DEVSHELL: android
jobs:
  lint:
    name: Lint (Android)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
      - uses: taiki-e/install-action@just
      - name: Build Android bindings (required for lint)
        run: just android build
      - name: Lint Android SDK
        run: just android lint
