name: Lint iOS
on:
  workflow_call:
env:
  NIX_DEVSHELL: ios
jobs:
  lint:
    name: Lint (iOS)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
      - uses: taiki-e/install-action@just
      - name: Lint iOS SDK
        run: just ios lint
