name: Lint Node
on:
  workflow_call:
env:
  NIX_DEVSHELL: js
jobs:
  lint:
    name: Lint (Node)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
      - uses: taiki-e/install-action@just
      - name: Install dependencies
        run: just node install-ci
      - name: Lint Node bindings
        run: just node lint
