name: Lint Config
on:
  workflow_call:
env:
  NIX_DEVSHELL: rust
jobs:
  lint:
    name: Lint (Config)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
      - uses: taiki-e/install-action@just
      - name: Lint config files (TOML, Nix, shell)
        run: just lint-config
