name: Nightly Automation
on:
  schedule:
    - cron:  '0 10 * * 1'
  workflow_dispatch:
jobs:
  nightly-protos:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: bufbuild/buf-setup-action@v1.50.0
      - name: Update rust toolchains
        run: rustup update
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
           .
      - name: Generate Protos
        run: dev/gen_protos.sh
      - name: Install Taplo
        env:
          version: "0.9.3"
        run: |
          curl -Ls "https://github.com/tamasfe/taplo/releases/download/${{ env.version }}/taplo-full-linux-x86_64.gz" | \
          gzip -d > taplo && \
          chmod +x taplo && \
          sudo mv taplo /usr/local/bin/taplo
      - name: Run format check
        run: taplo format
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Nightly Protos
          title: Update Protos
          body: |
            - Nightly Proto Update

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: nightly-proto