name: Daily Sync Fork

on:
  schedule:
    - cron: '08 17 * * *'  # Every day at 1:00 AM UTC
  workflow_dispatch:      # Allows you to run it manually too

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Git
      run: |
        git config --global user.email "ryan@prasso.ai"
        git config --global user.name "Your Name"

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/xmtp/libxmtp.git
        git fetch upstream

    - name: Merge upstream into fork
      run: |
        git checkout main
        git merge upstream/main --no-edit || echo "No changes to merge"
        git push origin main
