name: Test WASM
on:
  workflow_call:
env:
  NIX_DEVSHELL: wasm
jobs:
  wasm-ci:
    name: Test (WASM)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: "true"
      - uses: taiki-e/install-action@just
      - name: Install dependencies
        run: just wasm install-ci
      - name: Start backend
        run: just backend up
      - name: Run WASM tests
        run: just wasm test
      - name: Run WASM integration tests
        run: just wasm test-integration
