name: Test Workspace with WebAssembly
on:
  push:
    branches:
      - main
  pull_request:
    # only run tests when related changes are made
    paths:
      - ".github/workflows/test-webassembly.yml"
      - "crates/xmtp_mls/src/**"
      - "crates/xmtp_id/src/**"
      - "crates/xmtp_db/**"
      - "crates/xmtp_api_d14n/**"
      - "crates/xmtp_content_types/**"
      - "crates/xmtp_proto/**"
      - "bindings/wasm/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo/**"
      - "rust-toolchain.toml"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
jobs:
  wasm-ci:
    name: WASM CI
    runs-on: warp-ubuntu-latest-x64-16x
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: 'true'
      - name: Install omnix
        run: nix profile install nixpkgs#omnix

      - name: Start Docker containers
        run: |
          nix build .#docker-mls_validation_service
          dev/docker/up
      - name: run tests
        run: om ci run .#wasm

  wasm-integration:
    name: WASM Integration Tests
    runs-on: warp-ubuntu-latest-x64-16x
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: 'true'
      - name: Start Docker containers
        run: |
          nix build .#docker-mls_validation_service
          dev/docker/up
      - name: webassembly integration tests
        working-directory: bindings/wasm
        run: |
          yarn
          yarn build:test
          yarn typecheck
          yarn playwright install
          yarn test:integration
