name: Test Android

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit Tests (Android)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: taiki-e/install-action@just
      - name: Start backend
        env:
          NIX_DEVSHELL: android
        run: just backend up
      - name: Run unit tests
        env:
          NIX_DEVSHELL: android
        run: just android test

  integration-tests:
    name: Integration Tests (Android)
    runs-on: warp-ubuntu-latest-x64-16x
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: taiki-e/install-action@just
      - name: Start backend
        env:
          NIX_DEVSHELL: android
        run: just backend up
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run integration tests
        timeout-minutes: 20
        env:
          NIX_DEVSHELL: android
          NIX_ANDROID_EMULATOR_FLAGS: "-no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -memory 4096 -partition-size 8192"
        run: just android test-integration
