name: Test Workspace with WebAssembly
on:
  push:
    branches:
      - main
  pull_request:
    # only run tests when related changes are made
    paths:
      - ".github/workflows/test-webassembly.yml"
      - "crates/xmtp_mls/src/**"
      - "crates/xmtp_id/src/**"
      - "crates/xmtp_db/**"
      - "crates/xmtp_api_d14n/**"
      - "crates/xmtp_content_types/**"
      - "crates/xmtp_proto/**"
      - "bindings/wasm/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo/**"
      - "rust-toolchain.toml"
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
jobs:
  test:
    name: Test
    runs-on: warp-ubuntu-latest-x64-16x
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix build --version
      - uses: cachix/cachix-action@v16
        with:
          name: xmtp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      #     - uses: nix-community/cache-nix-action@v6
      #       with:
      #         primary-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      #         paths: |
      #           ~/.cargo/bin/
      #           ~/.cargo/registry/index/
      #           ~/.cargo/registry/cache/
      #           ~/.cargo/git/db/
      #           target/
      - name: Install omnix
        run: nix profile install nixpkgs#omnix

      - name: Start Docker containers
        run: |
          nix build .#docker-mls_validation_service --accept-flake-config
          dev/docker/up
      - name: run tests
        run: om ci run .#wasm -- --accept-flake-config
      - name: webassembly integration tests
        working-directory: bindings/wasm
        run: |
          yarn
          yarn build:test
          yarn typecheck
          yarn playwright install
          yarn test:integration
