name: Test WASM
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
jobs:
  wasm-ci:
    name: Test (WASM)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: "true"
      - uses: taiki-e/install-action@just
      - name: Start Docker containers
        run: |
          nix build .#validation-service-image-musl64
          dev/docker/up
      - name: run tests
        run: just wasm test

  wasm-integration:
    name: WASM Integration Tests
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: "true"
      - name: Start Docker containers
        run: |
          nix build .#validation-service-image-musl64
          dev/docker/up
      # Ensure playwright version in nix matches that in package.json
      - uses: taiki-e/install-action@just
      - name: webassembly integration tests
        run: just wasm test-integration
