name: Test Bindings Check
on:
  workflow_call:
jobs:
  check-swift:
    runs-on: warp-macos-13-arm64-6x
    env:
      NIX_DEVSHELL: ios
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: "true"
      - uses: taiki-e/install-action@just
      - name: Check iOS bindings compile
        run: just ios check

  check-android:
    runs-on: warp-ubuntu-latest-x64-16x
    env:
      NIX_DEVSHELL: android
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: "true"
      - uses: taiki-e/install-action@just
      - name: Check Android bindings compile
        run: just android check
