name: Test Workspace with WebAssembly
on:
  push:
    branches:
      - main
  pull_request:
    # only run tests when related changes are made
    paths:
      - ".github/workflows/test-webassembly.yml"
      - "crates/xmtp_mls/src/**"
      - "crates/xmtp_id/src/**"
      - "crates/xmtp_db/**"
      - "crates/xmtp_api_d14n/**"
      - "crates/xmtp_content_types/**"
      - "crates/xmtp_proto/**"
      - "bindings/wasm/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo/**"
      - "rust-toolchain.toml"
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
jobs:
  test:
    name: Test
    runs-on: warp-ubuntu-latest-x64-8x
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install wasm-bindgen
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen@0.2.105
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
      - name: Start Docker containers
        run: |
          dev/build_validation_service_local
          dev/docker/up
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: xmtp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: test libraries
        run: |
          nix develop .#wasm --command \
            cargo test --locked --release -p xmtp_id -p xmtp_cryptography -p xmtp_api -p bindings_wasm -p xmtp_db -p xmtp_api_grpc
      - name: test d14n
        run: |
          nix develop .#wasm --command cargo test --locked --release -p xmtp_api_d14n
        working-directory: ./
      - name: test xmtp_mls client
        run: |
          nix develop .#wasm --command \
            cargo test --locked --release -p xmtp_mls -- --skip subscriptions:: --skip test_debug_pkg --skip test_double_sync_works_fine
        working-directory: ./
      - name: test xmtp_mls subscriptions
        run: |
          nix develop .#wasm --command \
            cargo test --locked --release -p xmtp_mls -- subscriptions::
        working-directory: ./
      - name: webassembly integration tests
        working-directory: bindings/wasm
        run: |
          yarn
          yarn build:test
          yarn typecheck
          yarn playwright install
          yarn test:integration
