name: Test Android

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit Tests (Android)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build bindings
        run: nix develop .#android --command ./sdks/android/dev/bindings
      - name: Start backend
        run: ./dev/up
      - name: Run unit tests
        run: nix develop .#android --command ./sdks/android/gradlew -p sdks/android library:testDebug

  integration-tests:
    name: Integration Tests (Android)
    runs-on: warp-ubuntu-latest-x64-16x
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Start backend
        run: ./dev/docker/up
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Build bindings
        run: nix develop .#android --command ./sdks/android/dev/bindings
      - name: Start emulator
        timeout-minutes: 10
        env:
          NIX_ANDROID_EMULATOR_FLAGS: "-no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -memory 4096 -partition-size 8192"
        run: nix develop .#android --command run-test-emulator
      - name: Run integration tests
        timeout-minutes: 20
        run: nix develop .#android --command ./sdks/android/gradlew -p sdks/android connectedCheck --continue
