on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: warp-ubuntu-latest-arm64-4x
    steps:
      - uses: actions/checkout@v2
      - run: dev/up
      - uses: nanasess/setup-chromedriver@master
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --headless --chrome
        working-directory: xmtp_api_grpc_gateway
